||Apples|Beef|Eggs|Potatoes|
|--|--|--|--|--|
|Carb|56.0|0.0|4.4|68.0|
|Protein|1.2|104.0|52.0|8.0|
|Fat|1.8|135.0|99.0|0.9|

* 이 행렬은 네 가지 다른 음식 100g당 탄수화물, 단백질, 지방이 가지는 칼로리를 보여준다.</br>
* 예를 들면 사과 100g에 들어 있는 탄수화물은 56 칼로리를 주고 단백질과 지방은 훨씬 적다.</br>
* 소고기 100g에 들어 있는 단백질은 104 칼로리를 주고 지방은 135칼로리를 준다
우리의 목적은 네 가지 음식의 탄수화물, 단백질, 지방이 주는 칼로리의 백분유을 구하는 것임.
* 예를 들어 Apples 컬럼의 모든 수를 다 더하면 100g의 사과는 59칼로리를 가지고 있다는 것을 알 수 있다.</br>
* 백분율을 계산한다면 사과에서 탄수화물이 주는 칼로리의 백분율은  56/59, 약 94.9%가 된다. 사과 칼로리의 대부분은 탄수화물인 것을 알 수 있다</br>

네 가지 음식안의 탄수화물, 단백질, 지방이 주는 칼로리의 백분율을 구하는 문제

In [1]:
import numpy as np

In [2]:
A = np.array([ [56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9] ])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [5]:
calsum = A.sum(axis=0)
print(calsum)
print(calsum.shape)

[ 59.  239.  155.4  76.9]
(4,)


In [6]:
print(calsum.reshape(1,4))

percentage = 100*A /calsum.reshape(1, 4) 
print(percentage)

[[ 59.  239.  155.4  76.9]]
[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
